services:
  backend:
    build:
      context: ./backend
      target: dev
    container_name: task-tracker-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/vendor
    environment:
      - ENV=development
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SESSION_SECRET=dev-secret-key-change-in-production
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_FROM=noreply@no.reply.com
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - redis
      - mailhog
    networks:
      - task-tracker-network

  redis:
    image: redis:7-alpine
    container_name: task-tracker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - task-tracker-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: task-tracker-mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    networks:
      - task-tracker-network

volumes:
  redis-data:

networks:
  task-tracker-network:
    driver: bridge